<?php

/**
 * BaseTrapialComments
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $comment_post_id
 * @property tinytext $comment_author
 * @property varchar $comment_author_email
 * @property varchar $comment_author_ip
 * @property text $comment_content
 * @property TrapialPosts $TrapialPosts
 * 
 * @method bigint          getCommentPostId()        Returns the current record's "comment_post_id" value
 * @method tinytext        getCommentAuthor()        Returns the current record's "comment_author" value
 * @method varchar         getCommentAuthorEmail()   Returns the current record's "comment_author_email" value
 * @method varchar         getCommentAuthorIp()      Returns the current record's "comment_author_ip" value
 * @method text            getCommentContent()       Returns the current record's "comment_content" value
 * @method TrapialPosts    getTrapialPosts()         Returns the current record's "TrapialPosts" value
 * @method TrapialComments setCommentPostId()        Sets the current record's "comment_post_id" value
 * @method TrapialComments setCommentAuthor()        Sets the current record's "comment_author" value
 * @method TrapialComments setCommentAuthorEmail()   Sets the current record's "comment_author_email" value
 * @method TrapialComments setCommentAuthorIp()      Sets the current record's "comment_author_ip" value
 * @method TrapialComments setCommentContent()       Sets the current record's "comment_content" value
 * @method TrapialComments setTrapialPosts()         Sets the current record's "TrapialPosts" value
 * 
 * @package    trapial
 * @subpackage model
 * @author     Rodrigo Campos H.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrapialComments extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trapial_comments');
        $this->hasColumn('comment_post_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('comment_author', 'tinytext', null, array(
             'type' => 'tinytext',
             'notnull' => true,
             ));
        $this->hasColumn('comment_author_email', 'varchar', 100, array(
             'type' => 'varchar',
             'notnull' => true,
             'default' => ' ',
             'length' => 100,
             ));
        $this->hasColumn('comment_author_ip', 'varchar', 100, array(
             'type' => 'varchar',
             'notnull' => true,
             'default' => ' ',
             'length' => 100,
             ));
        $this->hasColumn('comment_content', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrapialPosts', array(
             'local' => 'comment_post_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}