<?php

/**
 * BaseTrapialPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property longtext $post_content
 * @property text $post_title
 * 
 * @method longtext     getPostContent()  Returns the current record's "post_content" value
 * @method text         getPostTitle()    Returns the current record's "post_title" value
 * @method TrapialPosts setPostContent()  Sets the current record's "post_content" value
 * @method TrapialPosts setPostTitle()    Sets the current record's "post_title" value
 * 
 * @package    trapial
 * @subpackage model
 * @author     Rodrigo Campos H.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrapialPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trapial_posts');
        $this->hasColumn('post_content', 'longtext', null, array(
             'type' => 'longtext',
             'notnull' => true,
             ));
        $this->hasColumn('post_title', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $signable0 = new Doctrine_Template_Signable();
        $this->actAs($timestampable0);
        $this->actAs($signable0);
    }
}