<?php

/**
 * BaseTrapialEmployee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $firstName
 * @property text $lastName
 * @property text $profession
 * @property text $ocupation
 * @property text $picture
 * @property text $team
 * @property text $nivel
 * 
 * @method text            getFirstName()  Returns the current record's "firstName" value
 * @method text            getLastName()   Returns the current record's "lastName" value
 * @method text            getProfession() Returns the current record's "profession" value
 * @method text            getOcupation()  Returns the current record's "ocupation" value
 * @method text            getPicture()    Returns the current record's "picture" value
 * @method text            getTeam()       Returns the current record's "team" value
 * @method text            getNivel()      Returns the current record's "nivel" value
 * @method TrapialEmployee setFirstName()  Sets the current record's "firstName" value
 * @method TrapialEmployee setLastName()   Sets the current record's "lastName" value
 * @method TrapialEmployee setProfession() Sets the current record's "profession" value
 * @method TrapialEmployee setOcupation()  Sets the current record's "ocupation" value
 * @method TrapialEmployee setPicture()    Sets the current record's "picture" value
 * @method TrapialEmployee setTeam()       Sets the current record's "team" value
 * @method TrapialEmployee setNivel()      Sets the current record's "nivel" value
 * 
 * @package    trapial
 * @subpackage model
 * @author     Rodrigo Campos H.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrapialEmployee extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trapial_employee');
        $this->hasColumn('firstName', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('lastName', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('profession', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('ocupation', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('picture', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('team', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('nivel', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}