<?php

/**
 * BaseTrapialPhoto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $photo_category_id
 * @property text $photo_filename
 * @property TrapialPhotoCategory $TrapialPhotoCategory
 * 
 * @method bigint               getPhotoCategoryId()      Returns the current record's "photo_category_id" value
 * @method text                 getPhotoFilename()        Returns the current record's "photo_filename" value
 * @method TrapialPhotoCategory getTrapialPhotoCategory() Returns the current record's "TrapialPhotoCategory" value
 * @method TrapialPhoto         setPhotoCategoryId()      Sets the current record's "photo_category_id" value
 * @method TrapialPhoto         setPhotoFilename()        Sets the current record's "photo_filename" value
 * @method TrapialPhoto         setTrapialPhotoCategory() Sets the current record's "TrapialPhotoCategory" value
 * 
 * @package    trapial
 * @subpackage model
 * @author     Rodrigo Campos H.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrapialPhoto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trapial_photo');
        $this->hasColumn('photo_category_id', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('photo_filename', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TrapialPhotoCategory', array(
             'local' => 'photo_category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}