<?php

/**
 * BaseTrapialPhotoCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property text $category_name
 * @property text $category_description
 * @property Doctrine_Collection $Category
 * 
 * @method text                 getCategoryName()         Returns the current record's "category_name" value
 * @method text                 getCategoryDescription()  Returns the current record's "category_description" value
 * @method Doctrine_Collection  getCategory()             Returns the current record's "Category" collection
 * @method TrapialPhotoCategory setCategoryName()         Sets the current record's "category_name" value
 * @method TrapialPhotoCategory setCategoryDescription()  Sets the current record's "category_description" value
 * @method TrapialPhotoCategory setCategory()             Sets the current record's "Category" collection
 * 
 * @package    trapial
 * @subpackage model
 * @author     Rodrigo Campos H.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrapialPhotoCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trapial_photo_category');
        $this->hasColumn('category_name', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('category_description', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TrapialPhoto as Category', array(
             'local' => 'id',
             'foreign' => 'photo_category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}