<?php

/**
 * BaseTrapialPosts
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property bigint $post_author
 * @property longtext $post_content
 * @property text $post_title
 * @property bigint $comment_count
 * @property Doctrine_Collection $Comments
 * 
 * @method bigint              getPostAuthor()    Returns the current record's "post_author" value
 * @method longtext            getPostContent()   Returns the current record's "post_content" value
 * @method text                getPostTitle()     Returns the current record's "post_title" value
 * @method bigint              getCommentCount()  Returns the current record's "comment_count" value
 * @method Doctrine_Collection getComments()      Returns the current record's "Comments" collection
 * @method TrapialPosts        setPostAuthor()    Sets the current record's "post_author" value
 * @method TrapialPosts        setPostContent()   Sets the current record's "post_content" value
 * @method TrapialPosts        setPostTitle()     Sets the current record's "post_title" value
 * @method TrapialPosts        setCommentCount()  Sets the current record's "comment_count" value
 * @method TrapialPosts        setComments()      Sets the current record's "Comments" collection
 * 
 * @package    trapial
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrapialPosts extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trapial_posts');
        $this->hasColumn('post_author', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('post_content', 'longtext', null, array(
             'type' => 'longtext',
             'notnull' => true,
             ));
        $this->hasColumn('post_title', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('comment_count', 'bigint', 20, array(
             'type' => 'bigint',
             'notnull' => true,
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('TrapialComments as Comments', array(
             'local' => 'id',
             'foreign' => 'comment_post_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}