<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/03/28 21:05:10

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=trapial',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
