<?php

/**
 * TrapialPostsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrapialPostsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrapialPostsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrapialPosts');
    }
}