<?php

/**
 * TrapialEmployeeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrapialEmployeeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrapialEmployeeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrapialEmployee');
    }
}