<?php

/**
 * TrapialPhotoCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrapialPhotoCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrapialPhotoCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TrapialPhotoCategory');
    }
}