<?php

/**
 * TrapialEmployee
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    trapial
 * @subpackage model
 * @author     Rodrigo Campos H.
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class TrapialEmployee extends BaseTrapialEmployee
{
  public function getFullName(){
    return $this->getFirstName()." ".$this->getLastName();
  }
}
