# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
#all:

all:
  sf_guard_plugin:
    routes_register: false

  sf_guard_plugin:
    #success_signin_url:      /module/action # the plugin use the referer as default
    success_signout_url:    @homepage
