<?php
// auto-generated by sfViewConfigHandler
// date: 2011/03/28 21:17:26
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('menu.css', '', array ());
  $response->addStylesheet('nivo-slider.css', '', array ());
  $response->addJavascript('jquery-1.5.1.js', '', array ());
  $response->addJavascript('jquery.easing.1.3.js', '', array ());
  $response->addJavascript('menu.js', '', array ());
  $response->addJavascript('jquery.nivo.slider.js', '', array ());
  $response->addJavascript('slider.js', '', array ());
  $response->addJavascript('jquery.nivo.slider.pack.js', '', array ());


