# config/doctrine/schema.yml
---
TrapialPosts:
  actAs: { Timestampable: ~ }
  columns:
    post_author_id: { type: bigint(20), notnull: true }
    post_content:   { type: longtext, notnull: true }
    post_title:     { type: text, notnull: true }
    comment_count:  { type: bigint(20), notnull: true }
    #Falta poner columna para user_id, que correspondera a la tabla de usuarios cuando implente sfGuards.
  relations:
    sfGuardUser:    { onDelete: CASCADE, local: post_author_id, foreign: id, foreignAlias: AuthorId }

TrapialComments:
  actAs: {Timestampable: ~ }
  columns:
    comment_post_id:      { type: bigint(20), notnull: true, unique: true }
    comment_author:       { type: tinytext, notnull: true }
    comment_author_email: { type: varchar(100), notnull: true, default: ' ' }
    comment_author_ip:    { type: varchar(100), notnull: true, default: ' ' }
    comment_content:      { type: text, notnull: true }
  relations:
    TrapialPosts:         { onDelete: CASCADE, local: comment_post_id, foreign: id, foreignAlias: Comments }
    #Falta poner columna para user_id, que correspondera a la tabla de usuarios cuando implente sfGuards.
