# config/doctrine/schema.yml
---
TrapialPosts:
  actAs: { Timestampable: ~ , Signable: ~ }
  columns:
    post_content:   { type: longtext, notnull: true }
    post_title:     { type: text, notnull: true }
    post_file:      { type: text }
    #Falta poner contador de comentarios

#TrapialComments:
#  actAs: { Timestampable: ~ }
#  columns:
#    comment_post_id:      { type: bigint(20), notnull: true, unique: true }
#    comment_author:       { type: tinytext, notnull: true }
#    comment_author_email: { type: varchar(100), notnull: true, default: ' ' }
#    comment_author_ip:    { type: varchar(100), notnull: true, default: ' ' }
#    comment_content:      { type: text, notnull: true }
#  relations:
#    TrapialPosts:         { onDelete: CASCADE, local: comment_post_id, foreign: id, foreignAlias: Comments }
    #Falta poner columna para user_id, que correspondera a la tabla de usuarios cuando implente sfGuards.

TrapialEmployee:
  columns:
    firstName:  { type: text, notnull: true }
    lastName:   { type: text, notnull: true }
    profession: { type: text }
    ocupation:  { type: text, notnull: true }
    picture:    { type: text, notnull: true }
    team:       { type: text, notnull: true }
    nivel:      { type: text, notnull: true }
    